# Generated by Django 3.2.12 on 2023-08-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_auto_20230822_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='send_confirmation_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_agreement_update_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], default='landlord', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
